#!/usr/bin/env bash
# Regenerate typed clients/models for server (Python), UI (TS), and CLI (Python).
# Run from helix/openapi/. CI + pre-commit invoke this and fail on diff.

set -euo pipefail
HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
SPEC="$HERE/openapi.yaml"

ROOT="$(cd "$HERE/.." && pwd)"

# --- Server: datamodel-code-generator → pydantic v2 models ---------------------
SERVER_OUT="$ROOT/api/helix_api/generated"
mkdir -p "$SERVER_OUT"
echo "[server] generating Pydantic models → $SERVER_OUT"
uv run --with datamodel-code-generator \
    datamodel-codegen \
    --input "$SPEC" \
    --input-file-type openapi \
    --output "$SERVER_OUT/models.py" \
    --output-model-type pydantic_v2.BaseModel \
    --use-standard-collections \
    --use-union-operator \
    --field-constraints \
    --target-python-version 3.12
echo "# autogenerated — do not edit" > "$SERVER_OUT/__init__.py"
echo "from .models import *  # noqa: F401,F403" >> "$SERVER_OUT/__init__.py"

# --- UI: @hey-api/openapi-ts → typed fetch client ------------------------------
UI_OUT="$ROOT/ui/lib/api/generated"
mkdir -p "$UI_OUT"
echo "[ui] generating TS client → $UI_OUT"
( cd "$ROOT/ui" && npx --yes @hey-api/openapi-ts \
    -i "$SPEC" \
    -o lib/api/generated \
    -c @hey-api/client-fetch )

# --- CLI: openapi-python-client ------------------------------------------------
CLI_OUT="$ROOT/cli/helix_cli/generated"
echo "[cli] generating Python client → $CLI_OUT"
rm -rf "$CLI_OUT"
uv run --with openapi-python-client \
    openapi-python-client generate \
    --path "$SPEC" \
    --meta none \
    --output-path "$CLI_OUT"

echo "done."
